production:
  adapter: postgresql
  encoding: unicode
  database: faragni_prod
  pool: 5
  username: faragni
  password: faragni

development:
  adapter: postgresql
  encoding: unicode
  database: faragni_dev
  pool: 5
  username: faragni
  password: faragni

test:
  adapter: postgresql
  encoding: unicode
  database: faragni_test
  pool: 5
  username: faragni
  password: faragni